### ISSUE TITLE
Wrong download URL when trying to install Node v5.0.0

### ISSUE THREAD

**Issue by simevidas** [hakobera/nvmw#67]
`nvmw install v5.0.0` fails:

![capture](https://cloud.githubusercontent.com/assets/716405/10871203/a19ac8b2-80e0-11e5-93d6-0b6bd21c7b72.PNG)

Looks like the correct download URL is “https://nodejs.org/dist/v5.0.0/win-x64/node.exe” (notice the extra “win-” prefix in the directory).

**Comment by tolbertam** [comment]
#59 should solve this, it seems to be working for me from @TimothyGu's branch.

**Comment by modliszka** [comment]
I have this error too and it looks like it wasn't fixed. I want install `node v4.0.0`.

**Comment by Loyalsoldier** [comment]
It seems that the node.exe path on nodejs.org has changed since the release of v4. And the download URL is wrong of course.

**Comment by sjc01234** [comment]
So no resolution on this yet?  

@modliszka suggestion worked for me. Manually altering the .bat file.

**Comment by yoannmoinet** [comment]
@sjc01234 I don't know if this project is abandoned or not, but I had a fork for some time that seems to work ok (for me at least).

Look out for the [1-2 differences](https://github.com/yoannmoinet/nvmw#differences-with-hakoberas-upstream) with this one though.
